name             'docker'
maintainer       'Jean-Francois Theroux'
maintainer_email 'failshell@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures docker'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.6'
depends          'yum'
depends          'grub'
depends          'nginx', '>= 0.3.7'
